### PR TITLE
Added nullmailer's auth-login option

### PR DESCRIPTION
**Pull request by ggruening**
Hey,

thanks for your fantastic work and this very helpful role.

`nullmailer` has an option `--auth-login` (see [manpage](https://manpages.debian.org/testing/nullmailer/nullmailer-send.8.en.html#auth-login)). I missed an option in this role to activate this. This PR complements that.

My email provider didn't work without it. Hence: HTH :-)

Best regards
ggruening

### CODE REVIEW

**Comment by tboerger** [comment]
Thanks for the contributing, I would love to merge it but it would be easier if you are following conventional commits. The readme gets automatically updated after the merge of the pr.

**Comment by tboerger** [comment]
You can git rebase --interactive to merge both commits and than do a git commit --force :)

**Comment by tboerger** [comment]
No worry, I have taken the other path to squash the commits within the github UI :)
Thanks for your effort!

**Comment by tboerger** [comment]
As you can see I have rolled another release, [v1.1.0](https://github.com/rolehippie/nullmailer/releases/tag/v1.1.0) includes your contribution :)

**Comment by ggruening** [comment]
> Thanks for your effort!

You're welcome. Thanks for your contribution to my contribution! ;-)

**Pull request merged**
